name: kollegeapply
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1
  flutter_custom_clippers: ^2.1.0
  expansion_tile_group: ^1.2.4

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter



flutter: 
   assets:
    - assets/banner/
    - assets/character/
    - assets/icons/
    - assets/images/
    - assets/collegebuilding/
    - assets/logo/  


 

